### ISSUE TITLE
can't set annotations

### ISSUE THREAD

**Issue by emmaccacca** [securingsincity/react-ace#300]
# Problem

I tried to set annotations in my editor. However, it didn't work. Below is my Code:
![image](https://user-images.githubusercontent.com/5310448/32099777-4a9fc15c-bb44-11e7-853b-0191afba39ad.png)

## References

Progress on: #

**Comment by eminx** [comment]
Do you have any error, message or so appearing or??

**Comment by andrewbaldock** [comment]
Having the same issue with markers and annotations

**Comment by jvilk** [comment]
Can confirm: Annotations do not appear, regardless of settings.

I had to manually interact with the editor post-rendering, which works:

```{javascript}
  public componentDidMount() {
    this._updateAceEditor();
  }

  public componentDidUpdate() {
    this._updateAceEditor();
  }

  private _updateAceEditor() {
    const editor = this.refs.aceEditor.editor;
    const annotations = this._getAnnotations();
    editor.getSession().setAnnotations(annotations);
  }
```

**Comment by xmeow** [comment]
Same issue here, for now I can only insert by:
```
this.editor.getSession().setAnnotations([{
            row: 1,
            column: 0,
            text: "Strange error",
            type: "error" // also warning and information
        }]);
```

**Comment by eminx** [comment]
`setOptions={{userWorker: true}}` needs to be given as a prop.

For me, this has proven to work:
```
            <AceEditor
                mode={options.mode}
                theme={this.state.theme}
                value={text}
                setOptions={{
                  showLineNumbers: options.lineNumbers,
                  useWorker: false,
                  vScrollBarAlwaysVisible: true,
                  animatedScroll: true
                }}
                editorProps={{
                    $blockScrolling: Infinity
                }}
                scrollMargin={[5, 5, 5, 5]}
            />
```

**Comment by eminx** [comment]
Ah Sorry guys. You have to import the brace files for annotations first. Like this:

```
import brace from 'brace';
import 'brace/mode/javascript';
import 'brace/mode/json';
import 'brace/mode/xml';
```

**Comment by fiws** [comment]
annotations and markers don't seem to be reactive. 

I can set them at startup, but they never update the editor

**Comment by jotak** [comment]
Same here: the annotations are set when rendering the AceEditor for the first time after mounting. But after that, they won't get updated. I work it around by interacting directly with ace editor with an ObjectRef.

**Comment by jotak** [comment]
Investigating further, I tried to create a reproducer but it turned out to be difficult, cause indeed it was working well if I was just adding annotations without other changes.

I finally could write this reproducer: https://gist.github.com/jotak/7d3398f25182ba58d75bf6f82a1ae1b0

The bug comes only when we're adding annotations AND changing text. If text is unchanged, the annotations are fine.
Digging further it's related to the session management in ace. I'm not totally sure about that, but I think when the text is changed, a new session is created and the annotation change event fired somehow misses its session.

So my suggestion is to change the order of processing in `componentWillReceiveProps`, to process first with the editor value update and only then with the other updates that are tied to the session.

**Comment by Fredxingxing** [comment]
try this, work for me , **set annotations in ace's afterRender hook**
```
 useEffect(() => {
        const { editor } = editorEl.current || {};
        if (annotations.length && editor) {
            editor.renderer.once('afterRender').then(() => {
                editor.getSession().setAnnotations(annotations);
            });
        }
    }, [JSON.stringify(annotations)]);
```

**Comment by chengandguo** [comment]
Here is anothe solution , use async setAnnoations can succeed
like window.setTimeout
