### ISSUE TITLE
Differences CSS color tags showing between single editor and split editor

### ISSUE THREAD

**Issue by kidqn** [securingsincity/react-ace#337]
I face a problem about CSS showing that is when I add a CSS property such as:
 body {
    color: red;
}
in Monokai theme, css mode.
Simple editor shows body tag with white color
Split editor shows it with red color.

I want it shows body or any common CSS tags with red color in simple Editor. How can I do that? Thanks for any helps.

Dinh.

**Comment by securingsincity** [comment]
@kidqn i'm not sure what you mean. Are you asking how to style the text inside of ace? or are you asking something else? Can you provide more detail and please fill out the Issue template when submitting issues.

**Comment by vinyldarkscratch** [comment]
I think this problem is the same as one I'm experiencing whilst working on a contract webdev project.  It appears that there's an `.ace-tm` class being applied to the primary editor div (`#ace-editor`) that surrounds both of the editors within, which is overwriting the specified `theme` on the internal editors.  In other words, we're not setting the theme to the main editor.

Normal: 
<img width="1920" alt="Screen Shot 2020-02-14 at 23 28 06" src="https://user-images.githubusercontent.com/5179191/74583937-a8d30a80-4f81-11ea-97ec-17a4c88cf848.png">

Split:
<img width="1920" alt="Screen Shot 2020-02-14 at 23 33 08" src="https://user-images.githubusercontent.com/5179191/74584019-6c53de80-4f82-11ea-9586-212aec776fca.png">

I think I can whip up a fix for this, so I'll get something going!

**Comment by bluepeter** [comment]
Cool... no rush, I will head to bed soon.

**Comment by vinyldarkscratch** [comment]
(@bluepeter Looks like you might have commented on the wrong issue.  😛)

**Comment by bluepeter** [comment]
Just saying I am heading to sleep, so no rush on pushing out any code... won't be able to comment until tomorrow.
