### ISSUE TITLE
Editor scrolls out of view when focus in mobile browsers (chrome/safari)

### ISSUE THREAD

**Issue by malerba118** [securingsincity/react-ace#492]
# Problem

On mobile browsers when focusing on the text area, the window scrolls to the top left position (0,0). I'm not sure if i'm just not configuring the editor properly or if this is a defect. I've noticed it on mobile devices only in chrome and safari. Solutions i've tried include messing around with autoScrollEditorIntoView, setting font size gte 16pt (supposed to prevent zoom in mobile browsers), stopping event bubbling in onFocus handler, scrolling window to position in onFocus handler.

## Sample code to reproduce your issue

https://codesandbox.io/s/j2x143p69w

## References

Progress on: #

**Comment by burnjohn** [comment]
@malerba118 This issue was fixed in `1.4.2` version of `ace`

Link to the issue https://github.com/ajaxorg/ace/issues/3788

`react-ace` uses `brace` https://github.com/thlorenz/brace

Brace has `1.2.9` version of `ace`.

As I think it's better to create own wrapper for ace editor and use it in the app.

**Comment by securingsincity** [comment]
We upgraded to ace in version 8. This should be resolved
