### ISSUE TITLE
Brace problem with Babel...

### ISSUE THREAD

**Issue by DWboutin** [securingsincity/react-ace#64]
https://github.com/thlorenz/brace/issues/40#issuecomment-153139418

**Comment by stevehu** [comment]
A similar problem in Brace I just opened. 

https://github.com/thlorenz/brace/issues/42

**Comment by spoike** [comment]
I'm using babel-register and I ended up doing two things:

* importing a file (./.../Editor.js) that has an empty div
* In my browserify build, setting the browser field in package.json to the file that actually uses ReactAce (./.../Editor-browser.js). it defers the render with React Ace by using a state variable that is set during componentDidMount (with a setTimeout), so that the client-side and server-side renders don't differ, but renders ReactAce after the mount.

**Comment by stevehu** [comment]
@spoike I don't have any server side rendering at all. I end up have my own fixed version and install from github.

**Comment by spoike** [comment]
@stevehu I'm referring to the error @DWboutin had, which was exact with mine where I was rendering react-ace on server-side. There is no clear explanation on how to work around the problem that brace and react-ace has a direct reference to the window object. Thus my comment to pull out the editor in node environment completely and render it instead client-side only when the component was mounted.
