### ISSUE TITLE
Any example of how to support custom code completion?

### ISSUE THREAD

**Issue by andrerpena** [securingsincity/react-ace#69]
Hi. First, thanks for this awesome lib!
Is there any example of how to support custom code completion? I mean... I wanted to implement support for a small syntax I've been working on. It's not exactly a programming language like JavaScript.
Any idea?
Thank you very much.

**Comment by eemp** [comment]
@andrerpena , I think it should be pretty easy to make happen (not taking into account the complexity of your custom completer).  I can outline a quick example based on something similar I just did and looking around at ace docs.  

In order to enable completion, we need to use an ace extension:

```javascript
/* set up custom completer by using a ace extension */
import ace from 'brace'

/* figured out how to load the extension properly
 * by referring to ptmt's response in https://github.com/thlorenz/brace/issues/19
 */
import 'brace/ext/language_tools'
let langTools = ace.acequire('ace/ext/language_tools');
```

Setup the completer like this:

```javascript
/* your custom completer */
var customCompleter = {
      getCompletions: function(editor, session, pos, prefix, callback) {
           // your code
      }
 }
langTools.addCompleter(customCompleter);
```

Currently, there is an existing issue (#59) dealing with how additional editor options should be handled.  Without that I think we would need to hack it:

```javascript
/* in some render somewhere
 * need this refs hack to set an editor option (another open issue in this repo)
 * inspired by elijahsmith's response in https://github.com/securingsincity/react-ace/issues/65
 */
<AceEditor ref="code" ...>

// with that setup, you can do something like
this.refs.code.editor.setOption('enableBasicAutocompletion', true);
```

I apologize if any of that is odd or poor practice.  I am just starting out with react and just began using react-ace wrapper around ace.  Although, almost all of it is based on the work of others.

**Comment by andrerpena** [comment]
@eemp Sorry for the late response and thank you very much for the example. This seems fairly easy indeed. I'll try it. Thanks again.

**Comment by fijolekProjects** [comment]
No need for hacks, you can also pass all completers via enableBasicAutocompletion as an Array, like so:
```javascript
<AceEditor
  ...
  setOptions={{
    enableBasicAutocompletion: [this.yourCustomCompleter]
  }}
/>
```

**Comment by go299** [comment]
I added my own ompleter, but I need to press  ctr+space to show the competion,  Is there a way to show the completion automatically.

**Comment by hristo-vrigazov** [comment]
@go299 You just have to enable the option `enableLiveAutocompletion` in ace.

**Comment by oakland** [comment]
@fijolekProjects How to write a custom completer? Is there any docs about this?

**Comment by fijolekProjects** [comment]
@oakland Don't know about docs, but here's  working example https://github.com/TouK/nussknacker/blob/v0.0.9/ui/client/components/graph/ExpressionSuggest.js#L31
Basically it's an object with `getCompletions` method implemented. Hope it helps

**Comment by oakland** [comment]
@fijolekProjects Thanks a lot! I will try it out in my project.

**Comment by blurymind** [comment]
how do we trigger autocompletion without ctrl+space. What if we want it to trigger automatically
