### ISSUE TITLE
Importing Range with ace.require("ace/range") in ace.tsx fails with undefined error while ES6 import in split.tsx works correctly

### ISSUE THREAD

**Issue by johnjackweir** [securingsincity/react-ace#954]
# Problem

Importing Range with `ace.require("ace/range")` in `ace.tsx` returns undefined. This is in contrast to `split.tsx` which imports the same Range package from `react-brace` where everything works correctly.

I believe that there should be at least an option to import Range from `ace-builds` even if `window.ace` is defined when selecting the ace instance in [EditorOptions](https://github.com/securingsincity/react-ace/blob/fe9728b904f7e66bec0510089a341146cdb2c5e3/src/editorOptions.ts#L70) 

## Sample code to reproduce your issue

The following import [`ace.tsx`](https://github.com/securingsincity/react-ace/blob/fe9728b904f7e66bec0510089a341146cdb2c5e3/src/ace.tsx#L13) returns undefined
```
const ace = getAceInstance();
const { Range } = ace.require("ace/range");
```

While ES6 imports in [`split.tsx`](https://github.com/securingsincity/react-ace/blob/fe9728b904f7e66bec0510089a341146cdb2c5e3/src/split.tsx#L8) work correctly
```
import { Ace, Range } from "ace-builds";
```

## References

Progress on: #
I've raised a PR that addresses the issue here: https://github.com/securingsincity/react-ace/pull/955

**Comment by securingsincity** [comment]
Thanks @johnjackweir This is live with 9.2.0

**Comment by janory** [comment]
Hey @securingsincity & @johnjackweir!

This fix unfortunately broke @gchallen's [SSR fix](https://github.com/securingsincity/react-ace/pull/841) , because if we import the `Range` class directly from the `ace-builds` lib, the TS compiler can't erase the `ace-builds` lib import/require from the compiled code.

The compiler can only erase the `ace-builds` lib, if we only reference types from there.
`Range` is a class, therefore the compiled `ace.js` file will also contain the `var ace_builds_1 = require("ace-builds");` line.
Which breaks the SSR which was fixed by the above mentioned PR.
So the `getAceInstance` only makes sense if don't directly require the `ace-builds`, otherwise it won't help.

Actually `const { Range } = ace.require("ace/range");` compiles to `var Range = ace.require("ace/range").Range;` which works for me fine, it's not undefined.

@johnjackweir do you remember how could we reproduce this?
I was using the latest `main` version.
